@startuml class-diagram
  interface "INewsDB\n<b>interface INewsDB</b>" as INewsDB {
    +saveNews(title, category, description, source)
    +getNews()
    +deleteNews(id)
  }

  interface "IteratorAggregate\n<b>interface IteratorAggregate (SPL)</b>" as IteratorAggregate {
    +getIterator()
  }

  interface "Iterator\n<b>interface Iterator (SPL)</b>" as Iterator {
    +rewind()
    +valid()
    +next()
    +key()
    +current()
  }

  class "NewsDB\n<b>Класс NewsDB</b>" as NewsDB {
    +DB_NAME : string
    +RSS_NAME : string
    +RSS_TITLE : string
    +RSS_LINK : string
    -_db : PDO
    -items : array
    #getDb()
    +__construct()
    +__destruct()
    -getCategories()
    +getIterator()
    +saveNews(title, category, description, source)
    +getNews()
    +deleteNews(id)
    +createRss()
  }

  class "PDO\n<b>Встроенный класс PHP</b>" as PDO

  class "ArrayIterator\n<b>Встроенный класс PHP</b>" as ArrayIterator

  class "DOMDocument\n<b>Встроенный класс PHP</b>" as DOMDocument

  INewsDB <|-- NewsDB
  IteratorAggregate <|-- NewsDB
  Iterator <|.. ArrayIterator
  NewsDB *-- PDO
  NewsDB ..> ArrayIterator : <<create>>
  NewsDB ..> DOMDocument : <<create>>
@enduml
